let color = 'orange';
let colorR = 'red';
document.getElementById('btn').onclick = ()=>{
    let information = document.getElementById('input').value;
    let i = 0;
    let timeID = setInterval(()=>{
        if(i < information.length){
            switch(information[i]){
                case 'a':
                    clear();
                    document.getElementById('diode7_3').style.backgroundColor = color;
                    document.getElementById('diode6_3').style.backgroundColor = color;
                    document.getElementById('diode5_3').style.backgroundColor = color;
                    document.getElementById('diode4_3').style.backgroundColor = color;
                    document.getElementById('diode3_3').style.backgroundColor = color;
                    document.getElementById('diode7_6').style.backgroundColor = color;
                    document.getElementById('diode6_6').style.backgroundColor = color;
                    document.getElementById('diode5_6').style.backgroundColor = color;
                    document.getElementById('diode4_6').style.backgroundColor = color;
                    document.getElementById('diode3_6').style.backgroundColor = color;
                    document.getElementById('diode2_4').style.backgroundColor = color;
                    document.getElementById('diode2_5').style.backgroundColor = color;
                    document.getElementById('diode4_4').style.backgroundColor = color;
                    document.getElementById('diode4_5').style.backgroundColor = color;
                    break;
                case 'b':
                    clear();
                    document.getElementById('diode7_3').style.backgroundColor = color;
                    document.getElementById('diode6_3').style.backgroundColor = color;
                    document.getElementById('diode5_3').style.backgroundColor = color;
                    document.getElementById('diode4_3').style.backgroundColor = color;
                    document.getElementById('diode3_3').style.backgroundColor = color;
                    document.getElementById('diode2_3').style.backgroundColor = color;
                    document.getElementById('diode2_4').style.backgroundColor = color;
                    document.getElementById('diode2_5').style.backgroundColor = color;
                    document.getElementById('diode3_5').style.backgroundColor = color;
                    document.getElementById('diode4_4').style.backgroundColor = color;
                    document.getElementById('diode5_5').style.backgroundColor = color;
                    document.getElementById('diode6_5').style.backgroundColor = color;
                    document.getElementById('diode7_5').style.backgroundColor = color;
                    document.getElementById('diode7_4').style.backgroundColor = color;
                    break;
                case 'c':
                    clear();
                    document.getElementById('diode7_4').style.backgroundColor = color;
                    document.getElementById('diode6_3').style.backgroundColor = color;
                    document.getElementById('diode5_3').style.backgroundColor = color;
                    document.getElementById('diode4_3').style.backgroundColor = color;
                    document.getElementById('diode3_3').style.backgroundColor = color;
                    document.getElementById('diode2_4').style.backgroundColor = color;
                    document.getElementById('diode2_5').style.backgroundColor = color;
                    document.getElementById('diode2_6').style.backgroundColor = color;
                    document.getElementById('diode7_6').style.backgroundColor = color;
                    document.getElementById('diode7_5').style.backgroundColor = color;
                    break;
                case 'd':
                    clear();
                    document.getElementById('diode7_3').style.backgroundColor = color;
                    document.getElementById('diode6_3').style.backgroundColor = color;
                    document.getElementById('diode5_3').style.backgroundColor = color;
                    document.getElementById('diode4_3').style.backgroundColor = color;
                    document.getElementById('diode3_3').style.backgroundColor = color;
                    document.getElementById('diode2_3').style.backgroundColor = color;
                    document.getElementById('diode2_4').style.backgroundColor = color;
                    document.getElementById('diode2_5').style.backgroundColor = color;
                    document.getElementById('diode7_5').style.backgroundColor = color;
                    document.getElementById('diode7_4').style.backgroundColor = color;
                    document.getElementById('diode6_6').style.backgroundColor = color;
                    document.getElementById('diode5_6').style.backgroundColor = color;
                    document.getElementById('diode4_6').style.backgroundColor = color;
                    document.getElementById('diode3_6').style.backgroundColor = color;
                    break;
                case 'e':
                    clear();
                    document.getElementById('diode7_3').style.backgroundColor = color;
                    document.getElementById('diode6_3').style.backgroundColor = color;
                    document.getElementById('diode5_3').style.backgroundColor = color;
                    document.getElementById('diode4_3').style.backgroundColor = color;
                    document.getElementById('diode3_3').style.backgroundColor = color;
                    document.getElementById('diode2_3').style.backgroundColor = color;
                    document.getElementById('diode2_4').style.backgroundColor = color;
                    document.getElementById('diode2_5').style.backgroundColor = color;
                    document.getElementById('diode2_6').style.backgroundColor = color;
                    document.getElementById('diode4_6').style.backgroundColor = color;
                    document.getElementById('diode4_5').style.backgroundColor = color;
                    document.getElementById('diode4_4').style.backgroundColor = color;
                    document.getElementById('diode7_4').style.backgroundColor = color;
                    document.getElementById('diode7_5').style.backgroundColor = color;
                    document.getElementById('diode7_6').style.backgroundColor = color;
                    break;
                case 'f':
                    clear();
                    document.getElementById('diode7_3').style.backgroundColor = color;
                    document.getElementById('diode6_3').style.backgroundColor = color;
                    document.getElementById('diode5_3').style.backgroundColor = color;
                    document.getElementById('diode4_3').style.backgroundColor = color;
                    document.getElementById('diode3_3').style.backgroundColor = color;
                    document.getElementById('diode2_3').style.backgroundColor = color;
                    document.getElementById('diode2_4').style.backgroundColor = color;
                    document.getElementById('diode2_5').style.backgroundColor = color;
                    document.getElementById('diode2_6').style.backgroundColor = color;
                    document.getElementById('diode4_6').style.backgroundColor = color;
                    document.getElementById('diode4_5').style.backgroundColor = color;
                    document.getElementById('diode4_4').style.backgroundColor = color;
                    break;
                case 'g':
                    clear();
                    document.getElementById('diode7_4').style.backgroundColor = color;
                    document.getElementById('diode7_5').style.backgroundColor = color;
                    document.getElementById('diode7_6').style.backgroundColor = color;
                    document.getElementById('diode6_7').style.backgroundColor = color;
                    document.getElementById('diode5_7').style.backgroundColor = color;
                    document.getElementById('diode4_6').style.backgroundColor = color;
                    document.getElementById('diode4_5').style.backgroundColor = color;
                    document.getElementById('diode6_3').style.backgroundColor = color;
                    document.getElementById('diode5_3').style.backgroundColor = color;
                    document.getElementById('diode4_3').style.backgroundColor = color;
                    document.getElementById('diode3_3').style.backgroundColor = color;
                    document.getElementById('diode2_4').style.backgroundColor = color;
                    document.getElementById('diode2_5').style.backgroundColor = color;
                    document.getElementById('diode2_6').style.backgroundColor = color;
                    break;
                case 'h':
                    clear();
                    document.getElementById('diode7_3').style.backgroundColor = color;
                    document.getElementById('diode7_6').style.backgroundColor = color;
                    document.getElementById('diode6_3').style.backgroundColor = color;
                    document.getElementById('diode6_6').style.backgroundColor = color;
                    document.getElementById('diode5_3').style.backgroundColor = color;
                    document.getElementById('diode5_6').style.backgroundColor = color;
                    document.getElementById('diode4_3').style.backgroundColor = color;
                    document.getElementById('diode4_6').style.backgroundColor = color;
                    document.getElementById('diode3_3').style.backgroundColor = color;
                    document.getElementById('diode3_6').style.backgroundColor = color;
                    document.getElementById('diode2_3').style.backgroundColor = color;
                    document.getElementById('diode2_6').style.backgroundColor = color;
                    document.getElementById('diode4_4').style.backgroundColor = color;
                    document.getElementById('diode4_5').style.backgroundColor = color;
                    break;
                case 'i':
                    clear();
                    document.getElementById('diode4_5').style.backgroundColor = color;
                    document.getElementById('diode4_4').style.backgroundColor = color;
                    document.getElementById('diode3_4').style.backgroundColor = color;
                    document.getElementById('diode3_5').style.backgroundColor = color;
                    document.getElementById('diode5_5').style.backgroundColor = color;
                    document.getElementById('diode5_4').style.backgroundColor = color;
                    document.getElementById('diode6_4').style.backgroundColor = color;
                    document.getElementById('diode6_5').style.backgroundColor = color;
                    document.getElementById('diode7_5').style.backgroundColor = color;
                    document.getElementById('diode7_4').style.backgroundColor = color;
                    document.getElementById('diode2_4').style.backgroundColor = color;
                    document.getElementById('diode2_5').style.backgroundColor = color;
                    break;
                case 'j':
                    clear();
                    document.getElementById('diode2_5').style.backgroundColor = color;
                    document.getElementById('diode3_5').style.backgroundColor = color;
                    document.getElementById('diode4_5').style.backgroundColor = color;
                    document.getElementById('diode5_5').style.backgroundColor = color;
                    document.getElementById('diode6_5').style.backgroundColor = color;
                    document.getElementById('diode6_5').style.backgroundColor = color;
                    document.getElementById('diode7_4').style.backgroundColor = color;
                    document.getElementById('diode6_3').style.backgroundColor = color;
                    break;
                case 'k':
                    clear();
                    document.getElementById('diode7_3').style.backgroundColor = color;
                    document.getElementById('diode6_3').style.backgroundColor = color;
                    document.getElementById('diode5_3').style.backgroundColor = color;
                    document.getElementById('diode4_3').style.backgroundColor = color;
                    document.getElementById('diode3_3').style.backgroundColor = color;
                    document.getElementById('diode2_3').style.backgroundColor = color;
                    document.getElementById('diode4_4').style.backgroundColor = color;
                    document.getElementById('diode3_5').style.backgroundColor = color;
                    document.getElementById('diode2_6').style.backgroundColor = color;
                    document.getElementById('diode5_4').style.backgroundColor = color;
                    document.getElementById('diode6_5').style.backgroundColor = color;
                    document.getElementById('diode7_6').style.backgroundColor = color;
                    break;
                case 'l':
                    clear();
                    document.getElementById('diode7_3').style.backgroundColor = color;
                    document.getElementById('diode7_4').style.backgroundColor = color;
                    document.getElementById('diode7_5').style.backgroundColor = color;
                    document.getElementById('diode7_6').style.backgroundColor = color;
                    document.getElementById('diode6_3').style.backgroundColor = color;
                    document.getElementById('diode5_3').style.backgroundColor = color;
                    document.getElementById('diode4_3').style.backgroundColor = color;
                    document.getElementById('diode3_3').style.backgroundColor = color;
                    document.getElementById('diode2_3').style.backgroundColor = color;
                    break;
                case 'm':
                    clear();
                    document.getElementById('diode7_3').style.backgroundColor = color;
                    document.getElementById('diode6_3').style.backgroundColor = color;
                    document.getElementById('diode5_3').style.backgroundColor = color;
                    document.getElementById('diode4_3').style.backgroundColor = color;
                    document.getElementById('diode3_3').style.backgroundColor = color;
                    document.getElementById('diode2_3').style.backgroundColor = color;
                    document.getElementById('diode3_4').style.backgroundColor = color;
                    document.getElementById('diode4_5').style.backgroundColor = color;
                    document.getElementById('diode3_6').style.backgroundColor = color;
                    document.getElementById('diode7_7').style.backgroundColor = color;
                    document.getElementById('diode6_7').style.backgroundColor = color;
                    document.getElementById('diode5_7').style.backgroundColor = color;
                    document.getElementById('diode4_7').style.backgroundColor = color;
                    document.getElementById('diode3_7').style.backgroundColor = color;
                    document.getElementById('diode2_7').style.backgroundColor = color;
                    break;
                case 'n':
                    clear();
                    document.getElementById('diode7_3').style.backgroundColor = color;
                    document.getElementById('diode6_3').style.backgroundColor = color;
                    document.getElementById('diode5_3').style.backgroundColor = color;
                    document.getElementById('diode5_6').style.backgroundColor = color;
                    document.getElementById('diode4_3').style.backgroundColor = color;
                    document.getElementById('diode3_3').style.backgroundColor = color;
                    document.getElementById('diode2_3').style.backgroundColor = color;
                    document.getElementById('diode3_4').style.backgroundColor = color;
                    document.getElementById('diode4_5').style.backgroundColor = color;
                    document.getElementById('diode7_7').style.backgroundColor = color;
                    document.getElementById('diode6_7').style.backgroundColor = color;
                    document.getElementById('diode5_7').style.backgroundColor = color;
                    document.getElementById('diode4_7').style.backgroundColor = color;
                    document.getElementById('diode3_7').style.backgroundColor = color;
                    document.getElementById('diode2_7').style.backgroundColor = color;
                    break;
                case 'o':
                    clear();
                    document.getElementById('diode7_3').style.backgroundColor = color;
                    document.getElementById('diode6_2').style.backgroundColor = color;
                    document.getElementById('diode5_2').style.backgroundColor = color;
                    document.getElementById('diode4_2').style.backgroundColor = color;
                    document.getElementById('diode3_2').style.backgroundColor = color;
                    document.getElementById('diode2_3').style.backgroundColor = color;
                    document.getElementById('diode2_4').style.backgroundColor = color;
                    document.getElementById('diode2_5').style.backgroundColor = color;
                    document.getElementById('diode2_6').style.backgroundColor = color;
                    document.getElementById('diode3_7').style.backgroundColor = color;
                    document.getElementById('diode4_7').style.backgroundColor = color;
                    document.getElementById('diode5_7').style.backgroundColor = color;
                    document.getElementById('diode6_7').style.backgroundColor = color;
                    document.getElementById('diode7_6').style.backgroundColor = color;
                    document.getElementById('diode7_5').style.backgroundColor = color;
                    document.getElementById('diode7_4').style.backgroundColor = color;
                    break;
                case 'p':
                    clear();
                    document.getElementById('diode7_3').style.backgroundColor = color;
                    document.getElementById('diode6_3').style.backgroundColor = color;
                    document.getElementById('diode5_3').style.backgroundColor = color;
                    document.getElementById('diode4_3').style.backgroundColor = color;
                    document.getElementById('diode3_3').style.backgroundColor = color;
                    document.getElementById('diode2_3').style.backgroundColor = color;
                    document.getElementById('diode2_4').style.backgroundColor = color;
                    document.getElementById('diode2_5').style.backgroundColor = color;
                    document.getElementById('diode2_6').style.backgroundColor = color;
                    document.getElementById('diode3_6').style.backgroundColor = color;
                    document.getElementById('diode4_6').style.backgroundColor = color;
                    document.getElementById('diode5_4').style.backgroundColor = color;
                    document.getElementById('diode5_5').style.backgroundColor = color;
                    break;
                case 'q':
                    clear();
                    document.getElementById('diode7_3').style.backgroundColor = color;
                    document.getElementById('diode6_2').style.backgroundColor = color;
                    document.getElementById('diode5_2').style.backgroundColor = color;
                    document.getElementById('diode4_2').style.backgroundColor = color;
                    document.getElementById('diode3_2').style.backgroundColor = color;
                    document.getElementById('diode2_3').style.backgroundColor = color;
                    document.getElementById('diode2_4').style.backgroundColor = color;
                    document.getElementById('diode2_5').style.backgroundColor = color;
                    document.getElementById('diode2_6').style.backgroundColor = color;
                    document.getElementById('diode3_7').style.backgroundColor = color;
                    document.getElementById('diode4_7').style.backgroundColor = color;
                    document.getElementById('diode5_7').style.backgroundColor = color;
                    document.getElementById('diode6_7').style.backgroundColor = color;
                    document.getElementById('diode7_6').style.backgroundColor = color;
                    document.getElementById('diode7_5').style.backgroundColor = color;
                    document.getElementById('diode7_4').style.backgroundColor = color;
                    document.getElementById('diode5_5').style.backgroundColor = color;
                    document.getElementById('diode6_6').style.backgroundColor = color;
                    document.getElementById('diode7_7').style.backgroundColor = color;
                    document.getElementById('diode8_8').style.backgroundColor = color;
                    break;
                case 'r':
                    clear();
                    document.getElementById('diode7_3').style.backgroundColor = color;
                    document.getElementById('diode6_3').style.backgroundColor = color;
                    document.getElementById('diode5_3').style.backgroundColor = color;
                    document.getElementById('diode4_3').style.backgroundColor = color;
                    document.getElementById('diode3_3').style.backgroundColor = color;
                    document.getElementById('diode2_3').style.backgroundColor = color;
                    document.getElementById('diode2_4').style.backgroundColor = color;
                    document.getElementById('diode2_5').style.backgroundColor = color;
                    document.getElementById('diode2_6').style.backgroundColor = color;
                    document.getElementById('diode3_6').style.backgroundColor = color;
                    document.getElementById('diode4_6').style.backgroundColor = color;
                    document.getElementById('diode5_4').style.backgroundColor = color;
                    document.getElementById('diode5_5').style.backgroundColor = color;
                    document.getElementById('diode6_5').style.backgroundColor = color;
                    document.getElementById('diode7_6').style.backgroundColor = color;
                    break;
                case 's':
                    clear();
                    document.getElementById('diode2_3').style.backgroundColor = color;
                    document.getElementById('diode2_4').style.backgroundColor = color;
                    document.getElementById('diode2_5').style.backgroundColor = color;
                    document.getElementById('diode2_6').style.backgroundColor = color;
                    document.getElementById('diode4_3').style.backgroundColor = color;
                    document.getElementById('diode3_3').style.backgroundColor = color;
                    document.getElementById('diode4_5').style.backgroundColor = color;
                    document.getElementById('diode4_6').style.backgroundColor = color;
                    document.getElementById('diode4_4').style.backgroundColor = color;
                    document.getElementById('diode5_6').style.backgroundColor = color;
                    document.getElementById('diode6_6').style.backgroundColor = color;
                    document.getElementById('diode7_5').style.backgroundColor = color;
                    document.getElementById('diode7_4').style.backgroundColor = color;
                    document.getElementById('diode7_6').style.backgroundColor = color;
                    document.getElementById('diode7_3').style.backgroundColor = color;
                    break;
                case 't':
                    clear();
                    document.getElementById('diode2_4').style.backgroundColor = color;
                    document.getElementById('diode3_4').style.backgroundColor = color;
                    document.getElementById('diode4_4').style.backgroundColor = color;
                    document.getElementById('diode5_4').style.backgroundColor = color;
                    document.getElementById('diode6_4').style.backgroundColor = color;
                    document.getElementById('diode7_4').style.backgroundColor = color;
                    document.getElementById('diode7_5').style.backgroundColor = color;
                    document.getElementById('diode6_5').style.backgroundColor = color;
                    document.getElementById('diode5_5').style.backgroundColor = color;
                    document.getElementById('diode4_5').style.backgroundColor = color;
                    document.getElementById('diode3_5').style.backgroundColor = color;
                    document.getElementById('diode2_5').style.backgroundColor = color;
                    document.getElementById('diode2_3').style.backgroundColor = color;
                    document.getElementById('diode2_6').style.backgroundColor = color;
                    break;
                case 'u':
                    clear();
                    document.getElementById('diode7_5').style.backgroundColor = color;
                    document.getElementById('diode7_6').style.backgroundColor = color;
                    document.getElementById('diode6_2').style.backgroundColor = color;
                    document.getElementById('diode5_2').style.backgroundColor = color;
                    document.getElementById('diode4_2').style.backgroundColor = color;
                    document.getElementById('diode3_2').style.backgroundColor = color;
                    document.getElementById('diode2_2').style.backgroundColor = color;
                    document.getElementById('diode2_7').style.backgroundColor = color;
                    document.getElementById('diode3_7').style.backgroundColor = color;
                    document.getElementById('diode4_7').style.backgroundColor = color;
                    document.getElementById('diode5_7').style.backgroundColor = color;
                    document.getElementById('diode6_7').style.backgroundColor = color;
                    document.getElementById('diode7_3').style.backgroundColor = color;
                    document.getElementById('diode7_4').style.backgroundColor = color;
                    break;
                case 'v':
                    clear();
                    document.getElementById('diode4_7').style.backgroundColor = color;
                    document.getElementById('diode3_7').style.backgroundColor = color;
                    document.getElementById('diode2_7').style.backgroundColor = color;
                    document.getElementById('diode5_6').style.backgroundColor = color;
                    document.getElementById('diode6_5').style.backgroundColor = color;
                    document.getElementById('diode6_4').style.backgroundColor = color;
                    document.getElementById('diode5_3').style.backgroundColor = color;
                    document.getElementById('diode4_2').style.backgroundColor = color;
                    document.getElementById('diode3_2').style.backgroundColor = color;
                    document.getElementById('diode2_2').style.backgroundColor = color;
                    break;
                case 'w':
                    clear();
                    document.getElementById('diode4_7').style.backgroundColor = color;
                    document.getElementById('diode3_7').style.backgroundColor = color;
                    document.getElementById('diode2_7').style.backgroundColor = color;
                    document.getElementById('diode5_6').style.backgroundColor = color;
                    document.getElementById('diode6_5').style.backgroundColor = color;
                    document.getElementById('diode6_4').style.backgroundColor = color;
                    document.getElementById('diode5_3').style.backgroundColor = color;
                    document.getElementById('diode4_2').style.backgroundColor = color;
                    document.getElementById('diode3_2').style.backgroundColor = color;
                    document.getElementById('diode2_2').style.backgroundColor = color;             
                    document.getElementById('diode4_5').style.backgroundColor = color;             
                    document.getElementById('diode4_4').style.backgroundColor = color;   
                    break;
                case 'x':
                    clear();
                    document.getElementById('diode2_2').style.backgroundColor = color;   
                    document.getElementById('diode3_3').style.backgroundColor = color;   
                    document.getElementById('diode4_4').style.backgroundColor = color;   
                    document.getElementById('diode5_5').style.backgroundColor = color;   
                    document.getElementById('diode6_6').style.backgroundColor = color;   
                    document.getElementById('diode7_7').style.backgroundColor = color;   
                    document.getElementById('diode7_2').style.backgroundColor = color;   
                    document.getElementById('diode6_3').style.backgroundColor = color;   
                    document.getElementById('diode5_4').style.backgroundColor = color;   
                    document.getElementById('diode4_5').style.backgroundColor = color;   
                    document.getElementById('diode3_6').style.backgroundColor = color;   
                    document.getElementById('diode2_7').style.backgroundColor = color;  
                    break;
                case 'y':
                    clear();
                    document.getElementById('diode2_2').style.backgroundColor = color;   
                    document.getElementById('diode3_3').style.backgroundColor = color;   
                    document.getElementById('diode4_4').style.backgroundColor = color;   
                    document.getElementById('diode7_2').style.backgroundColor = color;   
                    document.getElementById('diode6_3').style.backgroundColor = color;   
                    document.getElementById('diode5_4').style.backgroundColor = color;   
                    document.getElementById('diode4_5').style.backgroundColor = color;   
                    document.getElementById('diode3_6').style.backgroundColor = color;   
                    document.getElementById('diode2_7').style.backgroundColor = color;  
                    break;
                case '/':
                    clear();
                    document.getElementById('diode2_3').style.backgroundColor = colorR;   
                    document.getElementById('diode3_2').style.backgroundColor = colorR;   
                    document.getElementById('diode3_5').style.backgroundColor = colorR;   
                    document.getElementById('diode3_4').style.backgroundColor = colorR;   
                    document.getElementById('diode2_6').style.backgroundColor = colorR;   
                    document.getElementById('diode3_7').style.backgroundColor = colorR;   
                    document.getElementById('diode4_2').style.backgroundColor = colorR;   
                    document.getElementById('diode5_2').style.backgroundColor = colorR;   
                    document.getElementById('diode6_3').style.backgroundColor = colorR;   
                    document.getElementById('diode7_5').style.backgroundColor = colorR;   
                    document.getElementById('diode7_4').style.backgroundColor = colorR;   
                    document.getElementById('diode6_6').style.backgroundColor = colorR;   
                    document.getElementById('diode5_7').style.backgroundColor = colorR;   
                    document.getElementById('diode4_7').style.backgroundColor = colorR;   
                    break;
                case 'а':
                    clear();
                    document.getElementById('diode7_3').style.backgroundColor = color;
                    document.getElementById('diode6_3').style.backgroundColor = color;
                    document.getElementById('diode5_3').style.backgroundColor = color;
                    document.getElementById('diode4_3').style.backgroundColor = color;
                    document.getElementById('diode3_3').style.backgroundColor = color;
                    document.getElementById('diode7_6').style.backgroundColor = color;
                    document.getElementById('diode6_6').style.backgroundColor = color;
                    document.getElementById('diode5_6').style.backgroundColor = color;
                    document.getElementById('diode4_6').style.backgroundColor = color;
                    document.getElementById('diode3_6').style.backgroundColor = color;
                    document.getElementById('diode2_4').style.backgroundColor = color;
                    document.getElementById('diode2_5').style.backgroundColor = color;
                    document.getElementById('diode4_4').style.backgroundColor = color;
                    document.getElementById('diode4_5').style.backgroundColor = color;
                    break;
                case 'б':
                    clear();
                    document.getElementById('diode7_3').style.backgroundColor = color;
                    document.getElementById('diode6_3').style.backgroundColor = color;
                    document.getElementById('diode5_3').style.backgroundColor = color;
                    document.getElementById('diode4_3').style.backgroundColor = color;
                    document.getElementById('diode3_3').style.backgroundColor = color;
                    document.getElementById('diode2_3').style.backgroundColor = color;
                    document.getElementById('diode2_4').style.backgroundColor = color;
                    document.getElementById('diode2_5').style.backgroundColor = color;
                    document.getElementById('diode2_6').style.backgroundColor = color;
                    document.getElementById('diode7_6').style.backgroundColor = color;
                    document.getElementById('diode7_5').style.backgroundColor = color;
                    document.getElementById('diode7_4').style.backgroundColor = color;
                    document.getElementById('diode6_6').style.backgroundColor = color;
                    document.getElementById('diode5_6').style.backgroundColor = color;
                    document.getElementById('diode4_5').style.backgroundColor = color;
                    document.getElementById('diode4_4').style.backgroundColor = color;
                    document.getElementById('diode4_6').style.backgroundColor = color;
                    break;
                case 'в':
                    clear();
                    document.getElementById('diode7_3').style.backgroundColor = color;
                    document.getElementById('diode6_3').style.backgroundColor = color;
                    document.getElementById('diode5_3').style.backgroundColor = color;
                    document.getElementById('diode4_3').style.backgroundColor = color;
                    document.getElementById('diode3_3').style.backgroundColor = color;
                    document.getElementById('diode2_3').style.backgroundColor = color;
                    document.getElementById('diode2_4').style.backgroundColor = color;
                    document.getElementById('diode2_5').style.backgroundColor = color;
                    document.getElementById('diode2_6').style.backgroundColor = color;
                    document.getElementById('diode7_6').style.backgroundColor = color;
                    document.getElementById('diode7_5').style.backgroundColor = color;
                    document.getElementById('diode7_4').style.backgroundColor = color;
                    document.getElementById('diode6_6').style.backgroundColor = color;
                    document.getElementById('diode5_6').style.backgroundColor = color;
                    document.getElementById('diode4_5').style.backgroundColor = color;
                    document.getElementById('diode4_4').style.backgroundColor = color;
                    document.getElementById('diode4_6').style.backgroundColor = color;
                    document.getElementById('diode3_5').style.backgroundColor = color;
                    break;
                case 'г':
                    clear();
                    document.getElementById('diode7_3').style.backgroundColor = color;
                    document.getElementById('diode6_3').style.backgroundColor = color;
                    document.getElementById('diode5_3').style.backgroundColor = color;
                    document.getElementById('diode4_3').style.backgroundColor = color;
                    document.getElementById('diode3_3').style.backgroundColor = color;
                    document.getElementById('diode2_3').style.backgroundColor = color;
                    document.getElementById('diode2_4').style.backgroundColor = color;
                    document.getElementById('diode2_5').style.backgroundColor = color;
                    document.getElementById('diode2_6').style.backgroundColor = color;
                    break;
                case 'д':
                    clear();
                    document.getElementById('diode2_4').style.backgroundColor = color;
                    document.getElementById('diode2_5').style.backgroundColor = color;
                    document.getElementById('diode3_6').style.backgroundColor = color;
                    document.getElementById('diode3_3').style.backgroundColor = color;
                    document.getElementById('diode4_3').style.backgroundColor = color;
                    document.getElementById('diode4_6').style.backgroundColor = color;
                    document.getElementById('diode5_6').style.backgroundColor = color;
                    document.getElementById('diode5_3').style.backgroundColor = color;
                    document.getElementById('diode6_3').style.backgroundColor = color;
                    document.getElementById('diode6_4').style.backgroundColor = color;
                    document.getElementById('diode6_5').style.backgroundColor = color;
                    document.getElementById('diode6_6').style.backgroundColor = color;
                    document.getElementById('diode6_7').style.backgroundColor = color;
                    document.getElementById('diode6_2').style.backgroundColor = color;
                    document.getElementById('diode7_7').style.backgroundColor = color;
                    document.getElementById('diode7_2').style.backgroundColor = color;
                    break;
                case 'є':
                    clear();
                    document.getElementById('diode2_4').style.backgroundColor = color;
                    document.getElementById('diode2_5').style.backgroundColor = color;
                    document.getElementById('diode3_3').style.backgroundColor = color;
                    document.getElementById('diode4_3').style.backgroundColor = color;
                    document.getElementById('diode6_4').style.backgroundColor = color;
                    document.getElementById('diode5_3').style.backgroundColor = color;
                    document.getElementById('diode6_5').style.backgroundColor = color;
                    document.getElementById('diode4_5').style.backgroundColor = color;
                    document.getElementById('diode4_4').style.backgroundColor = color;
                    break;
                case 'е':
                    clear();
                    document.getElementById('diode2_4').style.backgroundColor = color;
                    document.getElementById('diode2_5').style.backgroundColor = color;
                    document.getElementById('diode3_3').style.backgroundColor = color;
                    document.getElementById('diode4_3').style.backgroundColor = color;
                    document.getElementById('diode7_4').style.backgroundColor = color;
                    document.getElementById('diode5_3').style.backgroundColor = color;
                    document.getElementById('diode6_3').style.backgroundColor = color;
                    document.getElementById('diode7_5').style.backgroundColor = color;
                    document.getElementById('diode3_6').style.backgroundColor = color;
                    document.getElementById('diode4_4').style.backgroundColor = color;
                    document.getElementById('diode4_5').style.backgroundColor = color;
                    break;
                case 'ж':
                    clear();
                    document.getElementById('diode2_2').style.backgroundColor = color;   
                    document.getElementById('diode3_3').style.backgroundColor = color;   
                    document.getElementById('diode4_4').style.backgroundColor = color;   
                    document.getElementById('diode5_5').style.backgroundColor = color;   
                    document.getElementById('diode6_6').style.backgroundColor = color;   
                    document.getElementById('diode7_7').style.backgroundColor = color;   
                    document.getElementById('diode7_2').style.backgroundColor = color;   
                    document.getElementById('diode6_3').style.backgroundColor = color;   
                    document.getElementById('diode5_4').style.backgroundColor = color;   
                    document.getElementById('diode4_5').style.backgroundColor = color;   
                    document.getElementById('diode3_6').style.backgroundColor = color;   
                    document.getElementById('diode2_7').style.backgroundColor = color;  
                    document.getElementById('diode2_4').style.backgroundColor = color;  
                    document.getElementById('diode2_5').style.backgroundColor = color;  
                    document.getElementById('diode3_4').style.backgroundColor = color;  
                    document.getElementById('diode3_5').style.backgroundColor = color;  
                    document.getElementById('diode5_5').style.backgroundColor = color;  
                    document.getElementById('diode5_4').style.backgroundColor = color;  
                    document.getElementById('diode6_4').style.backgroundColor = color;  
                    document.getElementById('diode6_5').style.backgroundColor = color;  
                    document.getElementById('diode7_5').style.backgroundColor = color;  
                    document.getElementById('diode7_4').style.backgroundColor = color;  
                    break;
                case 'з':
                    clear();
                    document.getElementById('diode2_3').style.backgroundColor = color;  
                    document.getElementById('diode2_4').style.backgroundColor = color;  
                    document.getElementById('diode2_5').style.backgroundColor = color;  
                    document.getElementById('diode3_6').style.backgroundColor = color;   
                    document.getElementById('diode4_5').style.backgroundColor = color;  
                    document.getElementById('diode4_4').style.backgroundColor = color;    
                    document.getElementById('diode5_6').style.backgroundColor = color;  
                    document.getElementById('diode6_6').style.backgroundColor = color;  
                    document.getElementById('diode7_3').style.backgroundColor = color;  
                    document.getElementById('diode7_4').style.backgroundColor = color;  
                    document.getElementById('diode7_5').style.backgroundColor = color; 
                    break;
                case 'и':
                    clear();
                    document.getElementById('diode7_3').style.backgroundColor = color;
                    document.getElementById('diode6_3').style.backgroundColor = color;
                    document.getElementById('diode5_3').style.backgroundColor = color;
                    document.getElementById('diode4_3').style.backgroundColor = color;
                    document.getElementById('diode3_3').style.backgroundColor = color;
                    document.getElementById('diode2_3').style.backgroundColor = color;
                    document.getElementById('diode6_4').style.backgroundColor = color;
                    document.getElementById('diode5_5').style.backgroundColor = color;
                    document.getElementById('diode7_6').style.backgroundColor = color;
                    document.getElementById('diode6_6').style.backgroundColor = color;
                    document.getElementById('diode5_6').style.backgroundColor = color;
                    document.getElementById('diode4_6').style.backgroundColor = color;
                    document.getElementById('diode3_6').style.backgroundColor = color;
                    document.getElementById('diode2_6').style.backgroundColor = color;
                    break;
                case 'і':
                    clear();
                    document.getElementById('diode4_5').style.backgroundColor = color;
                    document.getElementById('diode4_4').style.backgroundColor = color;
                    document.getElementById('diode5_5').style.backgroundColor = color;
                    document.getElementById('diode5_4').style.backgroundColor = color;
                    document.getElementById('diode6_4').style.backgroundColor = color;
                    document.getElementById('diode6_5').style.backgroundColor = color;
                    document.getElementById('diode7_5').style.backgroundColor = color;
                    document.getElementById('diode7_4').style.backgroundColor = color;
                    document.getElementById('diode2_4').style.backgroundColor = color;
                    document.getElementById('diode2_5').style.backgroundColor = color;
                    break;
                case 'й':
                    clear();
                    document.getElementById('diode7_3').style.backgroundColor = color;
                    document.getElementById('diode6_3').style.backgroundColor = color;
                    document.getElementById('diode5_3').style.backgroundColor = color;
                    document.getElementById('diode4_3').style.backgroundColor = color;
                    document.getElementById('diode2_5').style.backgroundColor = color;
                    document.getElementById('diode6_4').style.backgroundColor = color;
                    document.getElementById('diode5_5').style.backgroundColor = color;
                    document.getElementById('diode7_6').style.backgroundColor = color;
                    document.getElementById('diode6_6').style.backgroundColor = color;
                    document.getElementById('diode5_6').style.backgroundColor = color;
                    document.getElementById('diode4_6').style.backgroundColor = color;
                    document.getElementById('diode2_4').style.backgroundColor = color;
                    break;
                case 'ї':
                    clear();
                    document.getElementById('diode4_5').style.backgroundColor = color;
                    document.getElementById('diode4_4').style.backgroundColor = color;
                    document.getElementById('diode5_5').style.backgroundColor = color;
                    document.getElementById('diode5_4').style.backgroundColor = color;
                    document.getElementById('diode6_4').style.backgroundColor = color;
                    document.getElementById('diode6_5').style.backgroundColor = color;
                    document.getElementById('diode7_5').style.backgroundColor = color;
                    document.getElementById('diode7_4').style.backgroundColor = color;
                    document.getElementById('diode2_4').style.backgroundColor = color;
                    document.getElementById('diode2_5').style.backgroundColor = color;
                    document.getElementById('diode3_6').style.backgroundColor = color;
                    document.getElementById('diode3_3').style.backgroundColor = color;
                    break;
                case 'к':
                    clear();
                    document.getElementById('diode7_3').style.backgroundColor = color;
                    document.getElementById('diode6_3').style.backgroundColor = color;
                    document.getElementById('diode5_3').style.backgroundColor = color;
                    document.getElementById('diode4_3').style.backgroundColor = color;
                    document.getElementById('diode3_3').style.backgroundColor = color;
                    document.getElementById('diode2_3').style.backgroundColor = color;
                    document.getElementById('diode4_4').style.backgroundColor = color;
                    document.getElementById('diode3_5').style.backgroundColor = color;
                    document.getElementById('diode2_6').style.backgroundColor = color;
                    document.getElementById('diode5_4').style.backgroundColor = color;
                    document.getElementById('diode6_5').style.backgroundColor = color;
                    document.getElementById('diode7_6').style.backgroundColor = color;
                    break;
                case 'л':
                    clear();
                    document.getElementById('diode2_6').style.backgroundColor = color;
                    document.getElementById('diode3_6').style.backgroundColor = color;
                    document.getElementById('diode4_6').style.backgroundColor = color;
                    document.getElementById('diode5_6').style.backgroundColor = color;
                    document.getElementById('diode6_6').style.backgroundColor = color;
                    document.getElementById('diode7_6').style.backgroundColor = color;
                    document.getElementById('diode2_4').style.backgroundColor = color;
                    document.getElementById('diode2_5').style.backgroundColor = color;
                    document.getElementById('diode3_3').style.backgroundColor = color;
                    document.getElementById('diode2_3').style.backgroundColor = color;
                    document.getElementById('diode4_3').style.backgroundColor = color;
                    document.getElementById('diode5_3').style.backgroundColor = color;
                    document.getElementById('diode6_3').style.backgroundColor = color;
                    document.getElementById('diode7_2').style.backgroundColor = color;
                    break;
                case 'м':
                    clear();
                    document.getElementById('diode7_3').style.backgroundColor = color;
                    document.getElementById('diode6_3').style.backgroundColor = color;
                    document.getElementById('diode5_3').style.backgroundColor = color;
                    document.getElementById('diode4_3').style.backgroundColor = color;
                    document.getElementById('diode3_3').style.backgroundColor = color;
                    document.getElementById('diode2_3').style.backgroundColor = color;
                    document.getElementById('diode3_4').style.backgroundColor = color;
                    document.getElementById('diode4_5').style.backgroundColor = color;
                    document.getElementById('diode3_6').style.backgroundColor = color;
                    document.getElementById('diode7_7').style.backgroundColor = color;
                    document.getElementById('diode6_7').style.backgroundColor = color;
                    document.getElementById('diode5_7').style.backgroundColor = color;
                    document.getElementById('diode4_7').style.backgroundColor = color;
                    document.getElementById('diode3_7').style.backgroundColor = color;
                    document.getElementById('diode2_7').style.backgroundColor = color;
                    break;
                case 'н':
                    clear();
                    document.getElementById('diode7_3').style.backgroundColor = color;
                    document.getElementById('diode6_3').style.backgroundColor = color;
                    document.getElementById('diode5_3').style.backgroundColor = color;
                    document.getElementById('diode4_3').style.backgroundColor = color;
                    document.getElementById('diode3_3').style.backgroundColor = color;
                    document.getElementById('diode2_3').style.backgroundColor = color;
                    document.getElementById('diode4_4').style.backgroundColor = color;
                    document.getElementById('diode4_5').style.backgroundColor = color;
                    document.getElementById('diode2_6').style.backgroundColor = color;
                    document.getElementById('diode3_6').style.backgroundColor = color;
                    document.getElementById('diode4_6').style.backgroundColor = color;
                    document.getElementById('diode5_6').style.backgroundColor = color;
                    document.getElementById('diode6_6').style.backgroundColor = color;
                    document.getElementById('diode7_6').style.backgroundColor = color;
                    break;
                case 'о':
                    clear();
                    document.getElementById('diode7_3').style.backgroundColor = color;
                    document.getElementById('diode6_2').style.backgroundColor = color;
                    document.getElementById('diode5_2').style.backgroundColor = color;
                    document.getElementById('diode4_2').style.backgroundColor = color;
                    document.getElementById('diode3_2').style.backgroundColor = color;
                    document.getElementById('diode2_3').style.backgroundColor = color;
                    document.getElementById('diode2_4').style.backgroundColor = color;
                    document.getElementById('diode2_5').style.backgroundColor = color;
                    document.getElementById('diode2_6').style.backgroundColor = color;
                    document.getElementById('diode3_7').style.backgroundColor = color;
                    document.getElementById('diode4_7').style.backgroundColor = color;
                    document.getElementById('diode5_7').style.backgroundColor = color;
                    document.getElementById('diode6_7').style.backgroundColor = color;
                    document.getElementById('diode7_6').style.backgroundColor = color;
                    document.getElementById('diode7_5').style.backgroundColor = color;
                    document.getElementById('diode7_4').style.backgroundColor = color;
                    break;
                case 'п':
                    clear();
                    document.getElementById('diode2_6').style.backgroundColor = color;
                    document.getElementById('diode3_6').style.backgroundColor = color;
                    document.getElementById('diode4_6').style.backgroundColor = color;
                    document.getElementById('diode5_6').style.backgroundColor = color;
                    document.getElementById('diode6_6').style.backgroundColor = color;
                    document.getElementById('diode7_6').style.backgroundColor = color;
                    document.getElementById('diode2_4').style.backgroundColor = color;
                    document.getElementById('diode2_5').style.backgroundColor = color;
                    document.getElementById('diode3_3').style.backgroundColor = color;
                    document.getElementById('diode2_3').style.backgroundColor = color;
                    document.getElementById('diode4_3').style.backgroundColor = color;
                    document.getElementById('diode5_3').style.backgroundColor = color;
                    document.getElementById('diode6_3').style.backgroundColor = color;
                    document.getElementById('diode7_3').style.backgroundColor = color;
                    break;
                case 'р':
                    clear();
                    document.getElementById('diode7_3').style.backgroundColor = color;
                    document.getElementById('diode6_3').style.backgroundColor = color;
                    document.getElementById('diode5_3').style.backgroundColor = color;
                    document.getElementById('diode4_3').style.backgroundColor = color;
                    document.getElementById('diode3_3').style.backgroundColor = color;
                    document.getElementById('diode2_3').style.backgroundColor = color;
                    document.getElementById('diode2_4').style.backgroundColor = color;
                    document.getElementById('diode2_5').style.backgroundColor = color;
                    document.getElementById('diode2_6').style.backgroundColor = color;
                    document.getElementById('diode3_6').style.backgroundColor = color;
                    document.getElementById('diode4_6').style.backgroundColor = color;
                    document.getElementById('diode5_4').style.backgroundColor = color;
                    document.getElementById('diode5_5').style.backgroundColor = color;
                    break;
                case 'с':
                    clear();
                    document.getElementById('diode7_4').style.backgroundColor = color;
                    document.getElementById('diode6_3').style.backgroundColor = color;
                    document.getElementById('diode5_3').style.backgroundColor = color;
                    document.getElementById('diode4_3').style.backgroundColor = color;
                    document.getElementById('diode3_3').style.backgroundColor = color;
                    document.getElementById('diode2_4').style.backgroundColor = color;
                    document.getElementById('diode2_5').style.backgroundColor = color;
                    document.getElementById('diode2_6').style.backgroundColor = color;
                    document.getElementById('diode7_6').style.backgroundColor = color;
                    document.getElementById('diode7_5').style.backgroundColor = color;
                    break;
                case 'т':
                    clear();
                    document.getElementById('diode2_4').style.backgroundColor = color;
                    document.getElementById('diode3_4').style.backgroundColor = color;
                    document.getElementById('diode4_4').style.backgroundColor = color;
                    document.getElementById('diode5_4').style.backgroundColor = color;
                    document.getElementById('diode6_4').style.backgroundColor = color;
                    document.getElementById('diode7_4').style.backgroundColor = color;
                    document.getElementById('diode7_5').style.backgroundColor = color;
                    document.getElementById('diode6_5').style.backgroundColor = color;
                    document.getElementById('diode5_5').style.backgroundColor = color;
                    document.getElementById('diode4_5').style.backgroundColor = color;
                    document.getElementById('diode3_5').style.backgroundColor = color;
                    document.getElementById('diode2_5').style.backgroundColor = color;
                    document.getElementById('diode2_3').style.backgroundColor = color;
                    document.getElementById('diode2_6').style.backgroundColor = color;
                    break;
                case 'у':
                    clear();
                    document.getElementById('diode2_2').style.backgroundColor = color;   
                    document.getElementById('diode3_3').style.backgroundColor = color;   
                    document.getElementById('diode4_4').style.backgroundColor = color;   
                    document.getElementById('diode7_2').style.backgroundColor = color;   
                    document.getElementById('diode6_3').style.backgroundColor = color;   
                    document.getElementById('diode5_4').style.backgroundColor = color;   
                    document.getElementById('diode4_5').style.backgroundColor = color;   
                    document.getElementById('diode3_6').style.backgroundColor = color;   
                    document.getElementById('diode2_7').style.backgroundColor = color;
                    break;
                case 'ф':
                    clear();
                    document.getElementById('diode4_5').style.backgroundColor = color;
                    document.getElementById('diode4_4').style.backgroundColor = color;
                    document.getElementById('diode3_4').style.backgroundColor = color;
                    document.getElementById('diode3_5').style.backgroundColor = color;
                    document.getElementById('diode5_5').style.backgroundColor = color;
                    document.getElementById('diode5_4').style.backgroundColor = color;
                    document.getElementById('diode6_4').style.backgroundColor = color;
                    document.getElementById('diode6_5').style.backgroundColor = color;
                    document.getElementById('diode7_5').style.backgroundColor = color;
                    document.getElementById('diode7_4').style.backgroundColor = color;
                    document.getElementById('diode2_4').style.backgroundColor = color;
                    document.getElementById('diode2_5').style.backgroundColor = color;
                    document.getElementById('diode3_3').style.backgroundColor = color;
                    document.getElementById('diode3_6').style.backgroundColor = color;
                    document.getElementById('diode4_2').style.backgroundColor = color;
                    document.getElementById('diode4_7').style.backgroundColor = color;
                    document.getElementById('diode5_3').style.backgroundColor = color;
                    document.getElementById('diode5_6').style.backgroundColor = color;
                    break;
                case 'х':
                    clear();
                    document.getElementById('diode2_2').style.backgroundColor = color;   
                    document.getElementById('diode3_3').style.backgroundColor = color;   
                    document.getElementById('diode4_4').style.backgroundColor = color;   
                    document.getElementById('diode5_5').style.backgroundColor = color;   
                    document.getElementById('diode6_6').style.backgroundColor = color;   
                    document.getElementById('diode7_7').style.backgroundColor = color;   
                    document.getElementById('diode7_2').style.backgroundColor = color;   
                    document.getElementById('diode6_3').style.backgroundColor = color;   
                    document.getElementById('diode5_4').style.backgroundColor = color;   
                    document.getElementById('diode4_5').style.backgroundColor = color;   
                    document.getElementById('diode3_6').style.backgroundColor = color;   
                    document.getElementById('diode2_7').style.backgroundColor = color; 
                    break;
                case 'ц':
                    clear();
                    document.getElementById('diode7_3').style.backgroundColor = color;
                    document.getElementById('diode6_3').style.backgroundColor = color;
                    document.getElementById('diode5_3').style.backgroundColor = color;
                    document.getElementById('diode4_3').style.backgroundColor = color;
                    document.getElementById('diode3_3').style.backgroundColor = color;
                    document.getElementById('diode2_3').style.backgroundColor = color;
                    document.getElementById('diode2_6').style.backgroundColor = color;
                    document.getElementById('diode3_6').style.backgroundColor = color;
                    document.getElementById('diode4_6').style.backgroundColor = color;
                    document.getElementById('diode5_6').style.backgroundColor = color;
                    document.getElementById('diode6_6').style.backgroundColor = color;
                    document.getElementById('diode7_6').style.backgroundColor = color;
                    document.getElementById('diode7_4').style.backgroundColor = color;
                    document.getElementById('diode7_5').style.backgroundColor = color;
                    document.getElementById('diode7_7').style.backgroundColor = color;
                    document.getElementById('diode8_6').style.backgroundColor = color;
                    break;
                case 'ч':
                    clear();
                    document.getElementById('diode5_3').style.backgroundColor = color;
                    document.getElementById('diode5_4').style.backgroundColor = color;
                    document.getElementById('diode5_5').style.backgroundColor = color;
                    document.getElementById('diode5_6').style.backgroundColor = color;
                    document.getElementById('diode4_3').style.backgroundColor = color;
                    document.getElementById('diode4_6').style.backgroundColor = color;
                    document.getElementById('diode3_3').style.backgroundColor = color;
                    document.getElementById('diode3_6').style.backgroundColor = color;
                    document.getElementById('diode2_3').style.backgroundColor = color;
                    document.getElementById('diode2_6').style.backgroundColor = color;
                    document.getElementById('diode6_6').style.backgroundColor = color;
                    document.getElementById('diode7_6').style.backgroundColor = color;
                    break;
                case 'ш':
                    clear();
                    document.getElementById('diode7_2').style.backgroundColor = color;
                    document.getElementById('diode6_2').style.backgroundColor = color;
                    document.getElementById('diode5_2').style.backgroundColor = color;
                    document.getElementById('diode4_2').style.backgroundColor = color;
                    document.getElementById('diode3_2').style.backgroundColor = color;
                    document.getElementById('diode2_2').style.backgroundColor = color;
                    document.getElementById('diode7_3').style.backgroundColor = color;
                    document.getElementById('diode7_4').style.backgroundColor = color;
                    document.getElementById('diode7_5').style.backgroundColor = color;
                    document.getElementById('diode7_6').style.backgroundColor = color;
                    document.getElementById('diode7_7').style.backgroundColor = color;
                    document.getElementById('diode2_7').style.backgroundColor = color;
                    document.getElementById('diode3_7').style.backgroundColor = color;
                    document.getElementById('diode4_7').style.backgroundColor = color;
                    document.getElementById('diode5_7').style.backgroundColor = color;
                    document.getElementById('diode6_7').style.backgroundColor = color;
                    document.getElementById('diode2_4').style.backgroundColor = color;
                    document.getElementById('diode2_5').style.backgroundColor = color;
                    document.getElementById('diode3_5').style.backgroundColor = color;
                    document.getElementById('diode3_4').style.backgroundColor = color;
                    document.getElementById('diode4_4').style.backgroundColor = color;
                    document.getElementById('diode4_5').style.backgroundColor = color;
                    document.getElementById('diode5_5').style.backgroundColor = color;
                    document.getElementById('diode5_4').style.backgroundColor = color;
                    document.getElementById('diode6_5').style.backgroundColor = color;
                    document.getElementById('diode6_4').style.backgroundColor = color;
                    break;
                case 'щ':
                    clear();
                    document.getElementById('diode7_2').style.backgroundColor = color;
                    document.getElementById('diode6_2').style.backgroundColor = color;
                    document.getElementById('diode5_2').style.backgroundColor = color;
                    document.getElementById('diode4_2').style.backgroundColor = color;
                    document.getElementById('diode3_2').style.backgroundColor = color;
                    document.getElementById('diode2_2').style.backgroundColor = color;
                    document.getElementById('diode7_3').style.backgroundColor = color;
                    document.getElementById('diode7_4').style.backgroundColor = color;
                    document.getElementById('diode7_5').style.backgroundColor = color;
                    document.getElementById('diode7_6').style.backgroundColor = color;
                    document.getElementById('diode7_7').style.backgroundColor = color;
                    document.getElementById('diode2_7').style.backgroundColor = color;
                    document.getElementById('diode3_7').style.backgroundColor = color;
                    document.getElementById('diode4_7').style.backgroundColor = color;
                    document.getElementById('diode5_7').style.backgroundColor = color;
                    document.getElementById('diode6_7').style.backgroundColor = color;
                    document.getElementById('diode2_4').style.backgroundColor = color;
                    document.getElementById('diode2_5').style.backgroundColor = color;
                    document.getElementById('diode3_5').style.backgroundColor = color;
                    document.getElementById('diode3_4').style.backgroundColor = color;
                    document.getElementById('diode4_4').style.backgroundColor = color;
                    document.getElementById('diode4_5').style.backgroundColor = color;
                    document.getElementById('diode5_5').style.backgroundColor = color;
                    document.getElementById('diode5_4').style.backgroundColor = color;
                    document.getElementById('diode6_5').style.backgroundColor = color;
                    document.getElementById('diode6_4').style.backgroundColor = color;
                    document.getElementById('diode7_8').style.backgroundColor = color;
                    document.getElementById('diode8_7').style.backgroundColor = color;
                    break;
                case 'ь':
                    clear();
                    document.getElementById('diode7_3').style.backgroundColor = color;
                    document.getElementById('diode6_3').style.backgroundColor = color;
                    document.getElementById('diode5_3').style.backgroundColor = color;
                    document.getElementById('diode4_3').style.backgroundColor = color;
                    document.getElementById('diode3_3').style.backgroundColor = color;
                    document.getElementById('diode2_3').style.backgroundColor = color;
                    document.getElementById('diode7_6').style.backgroundColor = color;
                    document.getElementById('diode7_5').style.backgroundColor = color;
                    document.getElementById('diode7_4').style.backgroundColor = color;
                    document.getElementById('diode6_6').style.backgroundColor = color;
                    document.getElementById('diode5_6').style.backgroundColor = color;
                    document.getElementById('diode4_5').style.backgroundColor = color;
                    document.getElementById('diode4_4').style.backgroundColor = color;
                    document.getElementById('diode4_6').style.backgroundColor = color;
                    break;
                case 'ю':
                    clear();
                    document.getElementById('diode7_3').style.backgroundColor = color;
                    document.getElementById('diode6_3').style.backgroundColor = color;
                    document.getElementById('diode5_3').style.backgroundColor = color;
                    document.getElementById('diode4_3').style.backgroundColor = color;
                    document.getElementById('diode3_3').style.backgroundColor = color;
                    document.getElementById('diode2_3').style.backgroundColor = color;
                    document.getElementById('diode4_4').style.backgroundColor = color;
                    document.getElementById('diode4_5').style.backgroundColor = color;
                    document.getElementById('diode3_5').style.backgroundColor = color;
                    document.getElementById('diode2_5').style.backgroundColor = color;
                    document.getElementById('diode2_6').style.backgroundColor = color;
                    document.getElementById('diode2_7').style.backgroundColor = color;
                    document.getElementById('diode3_7').style.backgroundColor = color;
                    document.getElementById('diode4_7').style.backgroundColor = color;
                    document.getElementById('diode5_7').style.backgroundColor = color;
                    document.getElementById('diode6_7').style.backgroundColor = color;
                    document.getElementById('diode7_7').style.backgroundColor = color;
                    document.getElementById('diode7_6').style.backgroundColor = color;
                    document.getElementById('diode7_5').style.backgroundColor = color;
                    document.getElementById('diode6_5').style.backgroundColor = color;
                    document.getElementById('diode5_5').style.backgroundColor = color;
                    break;
                case 'я':
                    clear();
                    document.getElementById('diode3_6').style.backgroundColor = color;
                    document.getElementById('diode2_6').style.backgroundColor = color;
                    document.getElementById('diode2_5').style.backgroundColor = color;
                    document.getElementById('diode2_4').style.backgroundColor = color;
                    document.getElementById('diode4_4').style.backgroundColor = color;
                    document.getElementById('diode3_4').style.backgroundColor = color;
                    document.getElementById('diode4_5').style.backgroundColor = color;
                    document.getElementById('diode4_6').style.backgroundColor = color;
                    document.getElementById('diode5_6').style.backgroundColor = color;
                    document.getElementById('diode6_6').style.backgroundColor = color;
                    document.getElementById('diode7_6').style.backgroundColor = color;
                    document.getElementById('diode5_5').style.backgroundColor = color;
                    document.getElementById('diode6_4').style.backgroundColor = color;
                    document.getElementById('diode7_3').style.backgroundColor = color;
                    break;
                case '1':
                    clear();
                    document.getElementById('diode2_5').style.backgroundColor = color;
                    document.getElementById('diode3_4').style.backgroundColor = color;
                    document.getElementById('diode4_3').style.backgroundColor = color;
                    document.getElementById('diode3_5').style.backgroundColor = color;
                    document.getElementById('diode4_5').style.backgroundColor = color;
                    document.getElementById('diode5_5').style.backgroundColor = color;
                    document.getElementById('diode6_5').style.backgroundColor = color;
                    document.getElementById('diode7_5').style.backgroundColor = color;
                    break;
                case '2':
                    clear();
                    document.getElementById('diode2_4').style.backgroundColor = color;
                    document.getElementById('diode2_5').style.backgroundColor = color;
                    document.getElementById('diode3_3').style.backgroundColor = color;
                    document.getElementById('diode3_6').style.backgroundColor = color;
                    document.getElementById('diode4_5').style.backgroundColor = color;
                    document.getElementById('diode5_4').style.backgroundColor = color;
                    document.getElementById('diode6_4').style.backgroundColor = color;
                    document.getElementById('diode6_5').style.backgroundColor = color;
                    document.getElementById('diode6_6').style.backgroundColor = color;
                    document.getElementById('diode6_3').style.backgroundColor = color;
                    break;
                case '3':
                    clear();
                    document.getElementById('diode2_4').style.backgroundColor = color;
                    document.getElementById('diode2_5').style.backgroundColor = color;
                    document.getElementById('diode3_3').style.backgroundColor = color;
                    document.getElementById('diode3_6').style.backgroundColor = color;
                    document.getElementById('diode4_5').style.backgroundColor = color;
                    document.getElementById('diode5_6').style.backgroundColor = color;
                    document.getElementById('diode6_6').style.backgroundColor = color;
                    document.getElementById('diode7_5').style.backgroundColor = color;
                    document.getElementById('diode7_4').style.backgroundColor = color;
                    document.getElementById('diode6_3').style.backgroundColor = color;
                    break;
                case '4':
                    clear();
                    document.getElementById('diode2_3').style.backgroundColor = color;
                    document.getElementById('diode3_3').style.backgroundColor = color;
                    document.getElementById('diode4_3').style.backgroundColor = color;
                    document.getElementById('diode5_3').style.backgroundColor = color;
                    document.getElementById('diode5_4').style.backgroundColor = color;
                    document.getElementById('diode5_5').style.backgroundColor = color;
                    document.getElementById('diode5_6').style.backgroundColor = color;
                    document.getElementById('diode2_6').style.backgroundColor = color;
                    document.getElementById('diode3_6').style.backgroundColor = color;
                    document.getElementById('diode4_6').style.backgroundColor = color;
                    document.getElementById('diode6_6').style.backgroundColor = color;
                    document.getElementById('diode7_6').style.backgroundColor = color;
                    break;
                case '5':
                    clear();
                    document.getElementById('diode2_3').style.backgroundColor = color;
                    document.getElementById('diode2_4').style.backgroundColor = color;
                    document.getElementById('diode2_5').style.backgroundColor = color;
                    document.getElementById('diode2_6').style.backgroundColor = color;
                    document.getElementById('diode3_3').style.backgroundColor = color;
                    document.getElementById('diode4_3').style.backgroundColor = color;
                    document.getElementById('diode4_4').style.backgroundColor = color;
                    document.getElementById('diode4_5').style.backgroundColor = color;
                    document.getElementById('diode4_6').style.backgroundColor = color;
                    document.getElementById('diode5_6').style.backgroundColor = color;
                    document.getElementById('diode6_6').style.backgroundColor = color;
                    document.getElementById('diode7_3').style.backgroundColor = color;
                    document.getElementById('diode7_4').style.backgroundColor = color;
                    document.getElementById('diode7_5').style.backgroundColor = color;
                    document.getElementById('diode7_6').style.backgroundColor = color;







            }
            i++;
        }
        else{
            clear();
            clearInterval(timeID);
        }
    }, 500)
    function clear(){
        document.getElementById('diode1_1').style.backgroundColor = 'white';
        document.getElementById('diode1_2').style.backgroundColor = 'white';
        document.getElementById('diode1_3').style.backgroundColor = 'white';
        document.getElementById('diode1_4').style.backgroundColor = 'white';
        document.getElementById('diode1_5').style.backgroundColor = 'white';
        document.getElementById('diode1_6').style.backgroundColor = 'white';
        document.getElementById('diode1_7').style.backgroundColor = 'white';
        document.getElementById('diode1_8').style.backgroundColor = 'white';
        
        document.getElementById('diode2_1').style.backgroundColor = 'white';
        document.getElementById('diode2_2').style.backgroundColor = 'white';
        document.getElementById('diode2_3').style.backgroundColor = 'white';
        document.getElementById('diode2_4').style.backgroundColor = 'white';
        document.getElementById('diode2_5').style.backgroundColor = 'white';
        document.getElementById('diode2_6').style.backgroundColor = 'white';
        document.getElementById('diode2_7').style.backgroundColor = 'white';
        document.getElementById('diode2_8').style.backgroundColor = 'white';
        
        document.getElementById('diode3_1').style.backgroundColor = 'white';
        document.getElementById('diode3_2').style.backgroundColor = 'white';
        document.getElementById('diode3_3').style.backgroundColor = 'white';
        document.getElementById('diode3_4').style.backgroundColor = 'white';
        document.getElementById('diode3_5').style.backgroundColor = 'white';
        document.getElementById('diode3_6').style.backgroundColor = 'white';
        document.getElementById('diode3_7').style.backgroundColor = 'white';
        document.getElementById('diode3_8').style.backgroundColor = 'white';
        
        document.getElementById('diode4_1').style.backgroundColor = 'white';
        document.getElementById('diode4_2').style.backgroundColor = 'white';
        document.getElementById('diode4_3').style.backgroundColor = 'white';
        document.getElementById('diode4_4').style.backgroundColor = 'white';
        document.getElementById('diode4_5').style.backgroundColor = 'white';
        document.getElementById('diode4_6').style.backgroundColor = 'white';
        document.getElementById('diode4_7').style.backgroundColor = 'white';
        document.getElementById('diode4_8').style.backgroundColor = 'white';
        
        document.getElementById('diode5_1').style.backgroundColor = 'white';
        document.getElementById('diode5_2').style.backgroundColor = 'white';
        document.getElementById('diode5_3').style.backgroundColor = 'white';
        document.getElementById('diode5_4').style.backgroundColor = 'white';
        document.getElementById('diode5_5').style.backgroundColor = 'white';
        document.getElementById('diode5_6').style.backgroundColor = 'white';
        document.getElementById('diode5_7').style.backgroundColor = 'white';
        document.getElementById('diode5_8').style.backgroundColor = 'white';
        
        document.getElementById('diode6_1').style.backgroundColor = 'white';
        document.getElementById('diode6_2').style.backgroundColor = 'white';
        document.getElementById('diode6_3').style.backgroundColor = 'white';
        document.getElementById('diode6_4').style.backgroundColor = 'white';
        document.getElementById('diode6_5').style.backgroundColor = 'white';
        document.getElementById('diode6_6').style.backgroundColor = 'white';
        document.getElementById('diode6_7').style.backgroundColor = 'white';
        document.getElementById('diode6_8').style.backgroundColor = 'white';
        
        document.getElementById('diode7_1').style.backgroundColor = 'white';
        document.getElementById('diode7_2').style.backgroundColor = 'white';
        document.getElementById('diode7_3').style.backgroundColor = 'white';
        document.getElementById('diode7_4').style.backgroundColor = 'white';
        document.getElementById('diode7_5').style.backgroundColor = 'white';
        document.getElementById('diode7_6').style.backgroundColor = 'white';
        document.getElementById('diode7_7').style.backgroundColor = 'white';
        document.getElementById('diode7_8').style.backgroundColor = 'white';
        
        document.getElementById('diode8_1').style.backgroundColor = 'white';
        document.getElementById('diode8_2').style.backgroundColor = 'white';
        document.getElementById('diode8_3').style.backgroundColor = 'white';
        document.getElementById('diode8_4').style.backgroundColor = 'white';
        document.getElementById('diode8_5').style.backgroundColor = 'white';
        document.getElementById('diode8_5').style.backgroundColor = 'white';
        document.getElementById('diode8_6').style.backgroundColor = 'white';
        document.getElementById('diode8_7').style.backgroundColor = 'white';
        document.getElementById('diode8_8').style.backgroundColor = 'white';
    }
}